### ISSUE TITLE
Use the functions in the public API at pandas.testing instead

### ISSUE THREAD

**Issue by almamunx** [almamunx/Covid-19-Dashboard#3]
At Data Exploration section code input 4, it shows "FutureWarning: pandas.util.testing is deprecated". Please fix as per suggestion.

**Comment by shaiful019** [comment]
It's a machine dependency problem. Before the warning, you've got a location of **__testing.py_** file. From there,

Replace:
`from pandas.util.testing import assert_frame_equal`

with
`from pandas.testing import assert_frame_equal`
